/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as GamesRouteImport } from './routes/games'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as GamesWheelRouteImport } from './routes/games/wheel'
import { Route as GamesVideoPokerRouteImport } from './routes/games/video-poker'
import { Route as GamesTowersRouteImport } from './routes/games/towers'
import { Route as GamesRouletteRouteImport } from './routes/games/roulette'
import { Route as GamesPlinkoRouteImport } from './routes/games/plinko'
import { Route as GamesMinesRouteImport } from './routes/games/mines'
import { Route as GamesLimboRouteImport } from './routes/games/limbo'
import { Route as GamesKenoRouteImport } from './routes/games/keno'
import { Route as GamesHiloRouteImport } from './routes/games/hilo'
import { Route as GamesGoalRouteImport } from './routes/games/goal'
import { Route as GamesDiceRouteImport } from './routes/games/dice'
import { Route as GamesDiamondsRouteImport } from './routes/games/diamonds'
import { Route as GamesCrashRouteImport } from './routes/games/crash'
import { Route as GamesBlackjackRouteImport } from './routes/games/blackjack'
import { Route as DashboardDepositRequestsRouteImport } from './routes/dashboard/deposit-requests'
import { Route as DashboardDepositRouteImport } from './routes/dashboard/deposit'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as AuthDataDeletionInstructionsRouteImport } from './routes/auth/data-deletion-instructions'
import { Route as AuthVerifyIndexRouteImport } from './routes/auth/verify/index'
import { Route as AuthVerifySuccessRouteImport } from './routes/auth/verify/success'
import { Route as AuthVerifyPendingRouteImport } from './routes/auth/verify/pending'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCommonNotificationsIndexRouteImport } from './routes/api/common/notifications/index'
import { Route as ApiUsersWalletBalanceRouteImport } from './routes/api/users/wallet/balance'
import { Route as ApiUsersDepositRequestRouteImport } from './routes/api/users/deposit/request'
import { Route as ApiCommonNotificationsAllRouteImport } from './routes/api/common/notifications/all'
import { Route as ApiAdminDepositRequestsRouteImport } from './routes/api/admin/deposit/requests'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const GamesWheelRoute = GamesWheelRouteImport.update({
  id: '/wheel',
  path: '/wheel',
  getParentRoute: () => GamesRoute,
} as any)
const GamesVideoPokerRoute = GamesVideoPokerRouteImport.update({
  id: '/video-poker',
  path: '/video-poker',
  getParentRoute: () => GamesRoute,
} as any)
const GamesTowersRoute = GamesTowersRouteImport.update({
  id: '/towers',
  path: '/towers',
  getParentRoute: () => GamesRoute,
} as any)
const GamesRouletteRoute = GamesRouletteRouteImport.update({
  id: '/roulette',
  path: '/roulette',
  getParentRoute: () => GamesRoute,
} as any)
const GamesPlinkoRoute = GamesPlinkoRouteImport.update({
  id: '/plinko',
  path: '/plinko',
  getParentRoute: () => GamesRoute,
} as any)
const GamesMinesRoute = GamesMinesRouteImport.update({
  id: '/mines',
  path: '/mines',
  getParentRoute: () => GamesRoute,
} as any)
const GamesLimboRoute = GamesLimboRouteImport.update({
  id: '/limbo',
  path: '/limbo',
  getParentRoute: () => GamesRoute,
} as any)
const GamesKenoRoute = GamesKenoRouteImport.update({
  id: '/keno',
  path: '/keno',
  getParentRoute: () => GamesRoute,
} as any)
const GamesHiloRoute = GamesHiloRouteImport.update({
  id: '/hilo',
  path: '/hilo',
  getParentRoute: () => GamesRoute,
} as any)
const GamesGoalRoute = GamesGoalRouteImport.update({
  id: '/goal',
  path: '/goal',
  getParentRoute: () => GamesRoute,
} as any)
const GamesDiceRoute = GamesDiceRouteImport.update({
  id: '/dice',
  path: '/dice',
  getParentRoute: () => GamesRoute,
} as any)
const GamesDiamondsRoute = GamesDiamondsRouteImport.update({
  id: '/diamonds',
  path: '/diamonds',
  getParentRoute: () => GamesRoute,
} as any)
const GamesCrashRoute = GamesCrashRouteImport.update({
  id: '/crash',
  path: '/crash',
  getParentRoute: () => GamesRoute,
} as any)
const GamesBlackjackRoute = GamesBlackjackRouteImport.update({
  id: '/blackjack',
  path: '/blackjack',
  getParentRoute: () => GamesRoute,
} as any)
const DashboardDepositRequestsRoute =
  DashboardDepositRequestsRouteImport.update({
    id: '/deposit-requests',
    path: '/deposit-requests',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDepositRoute = DashboardDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDataDeletionInstructionsRoute =
  AuthDataDeletionInstructionsRouteImport.update({
    id: '/auth/data-deletion-instructions',
    path: '/auth/data-deletion-instructions',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthVerifyIndexRoute = AuthVerifyIndexRouteImport.update({
  id: '/auth/verify/',
  path: '/auth/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifySuccessRoute = AuthVerifySuccessRouteImport.update({
  id: '/auth/verify/success',
  path: '/auth/verify/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyPendingRoute = AuthVerifyPendingRouteImport.update({
  id: '/auth/verify/pending',
  path: '/auth/verify/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommonNotificationsIndexRoute =
  ApiCommonNotificationsIndexRouteImport.update({
    id: '/api/common/notifications/',
    path: '/api/common/notifications/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUsersWalletBalanceRoute = ApiUsersWalletBalanceRouteImport.update({
  id: '/api/users/wallet/balance',
  path: '/api/users/wallet/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersDepositRequestRoute = ApiUsersDepositRequestRouteImport.update({
  id: '/api/users/deposit/request',
  path: '/api/users/deposit/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommonNotificationsAllRoute =
  ApiCommonNotificationsAllRouteImport.update({
    id: '/api/common/notifications/all',
    path: '/api/common/notifications/all',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminDepositRequestsRoute = ApiAdminDepositRequestsRouteImport.update({
  id: '/api/admin/deposit/requests',
  path: '/api/admin/deposit/requests',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/games': typeof GamesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/data-deletion-instructions': typeof AuthDataDeletionInstructionsRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/deposit': typeof DashboardDepositRoute
  '/dashboard/deposit-requests': typeof DashboardDepositRequestsRoute
  '/games/blackjack': typeof GamesBlackjackRoute
  '/games/crash': typeof GamesCrashRoute
  '/games/diamonds': typeof GamesDiamondsRoute
  '/games/dice': typeof GamesDiceRoute
  '/games/goal': typeof GamesGoalRoute
  '/games/hilo': typeof GamesHiloRoute
  '/games/keno': typeof GamesKenoRoute
  '/games/limbo': typeof GamesLimboRoute
  '/games/mines': typeof GamesMinesRoute
  '/games/plinko': typeof GamesPlinkoRoute
  '/games/roulette': typeof GamesRouletteRoute
  '/games/towers': typeof GamesTowersRoute
  '/games/video-poker': typeof GamesVideoPokerRoute
  '/games/wheel': typeof GamesWheelRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/games/': typeof GamesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/verify/pending': typeof AuthVerifyPendingRoute
  '/auth/verify/success': typeof AuthVerifySuccessRoute
  '/auth/verify': typeof AuthVerifyIndexRoute
  '/api/admin/deposit/requests': typeof ApiAdminDepositRequestsRoute
  '/api/common/notifications/all': typeof ApiCommonNotificationsAllRoute
  '/api/users/deposit/request': typeof ApiUsersDepositRequestRoute
  '/api/users/wallet/balance': typeof ApiUsersWalletBalanceRoute
  '/api/common/notifications': typeof ApiCommonNotificationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/data-deletion-instructions': typeof AuthDataDeletionInstructionsRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/deposit': typeof DashboardDepositRoute
  '/dashboard/deposit-requests': typeof DashboardDepositRequestsRoute
  '/games/blackjack': typeof GamesBlackjackRoute
  '/games/crash': typeof GamesCrashRoute
  '/games/diamonds': typeof GamesDiamondsRoute
  '/games/dice': typeof GamesDiceRoute
  '/games/goal': typeof GamesGoalRoute
  '/games/hilo': typeof GamesHiloRoute
  '/games/keno': typeof GamesKenoRoute
  '/games/limbo': typeof GamesLimboRoute
  '/games/mines': typeof GamesMinesRoute
  '/games/plinko': typeof GamesPlinkoRoute
  '/games/roulette': typeof GamesRouletteRoute
  '/games/towers': typeof GamesTowersRoute
  '/games/video-poker': typeof GamesVideoPokerRoute
  '/games/wheel': typeof GamesWheelRoute
  '/dashboard': typeof DashboardIndexRoute
  '/games': typeof GamesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/verify/pending': typeof AuthVerifyPendingRoute
  '/auth/verify/success': typeof AuthVerifySuccessRoute
  '/auth/verify': typeof AuthVerifyIndexRoute
  '/api/admin/deposit/requests': typeof ApiAdminDepositRequestsRoute
  '/api/common/notifications/all': typeof ApiCommonNotificationsAllRoute
  '/api/users/deposit/request': typeof ApiUsersDepositRequestRoute
  '/api/users/wallet/balance': typeof ApiUsersWalletBalanceRoute
  '/api/common/notifications': typeof ApiCommonNotificationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/games': typeof GamesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/data-deletion-instructions': typeof AuthDataDeletionInstructionsRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/deposit': typeof DashboardDepositRoute
  '/dashboard/deposit-requests': typeof DashboardDepositRequestsRoute
  '/games/blackjack': typeof GamesBlackjackRoute
  '/games/crash': typeof GamesCrashRoute
  '/games/diamonds': typeof GamesDiamondsRoute
  '/games/dice': typeof GamesDiceRoute
  '/games/goal': typeof GamesGoalRoute
  '/games/hilo': typeof GamesHiloRoute
  '/games/keno': typeof GamesKenoRoute
  '/games/limbo': typeof GamesLimboRoute
  '/games/mines': typeof GamesMinesRoute
  '/games/plinko': typeof GamesPlinkoRoute
  '/games/roulette': typeof GamesRouletteRoute
  '/games/towers': typeof GamesTowersRoute
  '/games/video-poker': typeof GamesVideoPokerRoute
  '/games/wheel': typeof GamesWheelRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/games/': typeof GamesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/verify/pending': typeof AuthVerifyPendingRoute
  '/auth/verify/success': typeof AuthVerifySuccessRoute
  '/auth/verify/': typeof AuthVerifyIndexRoute
  '/api/admin/deposit/requests': typeof ApiAdminDepositRequestsRoute
  '/api/common/notifications/all': typeof ApiCommonNotificationsAllRoute
  '/api/users/deposit/request': typeof ApiUsersDepositRequestRoute
  '/api/users/wallet/balance': typeof ApiUsersWalletBalanceRoute
  '/api/common/notifications/': typeof ApiCommonNotificationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/games'
    | '/notifications'
    | '/privacy'
    | '/terms'
    | '/auth/data-deletion-instructions'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/dashboard/deposit'
    | '/dashboard/deposit-requests'
    | '/games/blackjack'
    | '/games/crash'
    | '/games/diamonds'
    | '/games/dice'
    | '/games/goal'
    | '/games/hilo'
    | '/games/keno'
    | '/games/limbo'
    | '/games/mines'
    | '/games/plinko'
    | '/games/roulette'
    | '/games/towers'
    | '/games/video-poker'
    | '/games/wheel'
    | '/dashboard/'
    | '/games/'
    | '/api/auth/$'
    | '/auth/verify/pending'
    | '/auth/verify/success'
    | '/auth/verify'
    | '/api/admin/deposit/requests'
    | '/api/common/notifications/all'
    | '/api/users/deposit/request'
    | '/api/users/wallet/balance'
    | '/api/common/notifications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/notifications'
    | '/privacy'
    | '/terms'
    | '/auth/data-deletion-instructions'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/dashboard/deposit'
    | '/dashboard/deposit-requests'
    | '/games/blackjack'
    | '/games/crash'
    | '/games/diamonds'
    | '/games/dice'
    | '/games/goal'
    | '/games/hilo'
    | '/games/keno'
    | '/games/limbo'
    | '/games/mines'
    | '/games/plinko'
    | '/games/roulette'
    | '/games/towers'
    | '/games/video-poker'
    | '/games/wheel'
    | '/dashboard'
    | '/games'
    | '/api/auth/$'
    | '/auth/verify/pending'
    | '/auth/verify/success'
    | '/auth/verify'
    | '/api/admin/deposit/requests'
    | '/api/common/notifications/all'
    | '/api/users/deposit/request'
    | '/api/users/wallet/balance'
    | '/api/common/notifications'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/games'
    | '/notifications'
    | '/privacy'
    | '/terms'
    | '/auth/data-deletion-instructions'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/dashboard/deposit'
    | '/dashboard/deposit-requests'
    | '/games/blackjack'
    | '/games/crash'
    | '/games/diamonds'
    | '/games/dice'
    | '/games/goal'
    | '/games/hilo'
    | '/games/keno'
    | '/games/limbo'
    | '/games/mines'
    | '/games/plinko'
    | '/games/roulette'
    | '/games/towers'
    | '/games/video-poker'
    | '/games/wheel'
    | '/dashboard/'
    | '/games/'
    | '/api/auth/$'
    | '/auth/verify/pending'
    | '/auth/verify/success'
    | '/auth/verify/'
    | '/api/admin/deposit/requests'
    | '/api/common/notifications/all'
    | '/api/users/deposit/request'
    | '/api/users/wallet/balance'
    | '/api/common/notifications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  GamesRoute: typeof GamesRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AuthDataDeletionInstructionsRoute: typeof AuthDataDeletionInstructionsRoute
  AuthErrorRoute: typeof AuthErrorRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AuthVerifyPendingRoute: typeof AuthVerifyPendingRoute
  AuthVerifySuccessRoute: typeof AuthVerifySuccessRoute
  AuthVerifyIndexRoute: typeof AuthVerifyIndexRoute
  ApiAdminDepositRequestsRoute: typeof ApiAdminDepositRequestsRoute
  ApiCommonNotificationsAllRoute: typeof ApiCommonNotificationsAllRoute
  ApiUsersDepositRequestRoute: typeof ApiUsersDepositRequestRoute
  ApiUsersWalletBalanceRoute: typeof ApiUsersWalletBalanceRoute
  ApiCommonNotificationsIndexRoute: typeof ApiCommonNotificationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof GamesRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/games/wheel': {
      id: '/games/wheel'
      path: '/wheel'
      fullPath: '/games/wheel'
      preLoaderRoute: typeof GamesWheelRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/video-poker': {
      id: '/games/video-poker'
      path: '/video-poker'
      fullPath: '/games/video-poker'
      preLoaderRoute: typeof GamesVideoPokerRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/towers': {
      id: '/games/towers'
      path: '/towers'
      fullPath: '/games/towers'
      preLoaderRoute: typeof GamesTowersRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/roulette': {
      id: '/games/roulette'
      path: '/roulette'
      fullPath: '/games/roulette'
      preLoaderRoute: typeof GamesRouletteRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/plinko': {
      id: '/games/plinko'
      path: '/plinko'
      fullPath: '/games/plinko'
      preLoaderRoute: typeof GamesPlinkoRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/mines': {
      id: '/games/mines'
      path: '/mines'
      fullPath: '/games/mines'
      preLoaderRoute: typeof GamesMinesRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/limbo': {
      id: '/games/limbo'
      path: '/limbo'
      fullPath: '/games/limbo'
      preLoaderRoute: typeof GamesLimboRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/keno': {
      id: '/games/keno'
      path: '/keno'
      fullPath: '/games/keno'
      preLoaderRoute: typeof GamesKenoRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/hilo': {
      id: '/games/hilo'
      path: '/hilo'
      fullPath: '/games/hilo'
      preLoaderRoute: typeof GamesHiloRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/goal': {
      id: '/games/goal'
      path: '/goal'
      fullPath: '/games/goal'
      preLoaderRoute: typeof GamesGoalRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/dice': {
      id: '/games/dice'
      path: '/dice'
      fullPath: '/games/dice'
      preLoaderRoute: typeof GamesDiceRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/diamonds': {
      id: '/games/diamonds'
      path: '/diamonds'
      fullPath: '/games/diamonds'
      preLoaderRoute: typeof GamesDiamondsRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/crash': {
      id: '/games/crash'
      path: '/crash'
      fullPath: '/games/crash'
      preLoaderRoute: typeof GamesCrashRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/blackjack': {
      id: '/games/blackjack'
      path: '/blackjack'
      fullPath: '/games/blackjack'
      preLoaderRoute: typeof GamesBlackjackRouteImport
      parentRoute: typeof GamesRoute
    }
    '/dashboard/deposit-requests': {
      id: '/dashboard/deposit-requests'
      path: '/deposit-requests'
      fullPath: '/dashboard/deposit-requests'
      preLoaderRoute: typeof DashboardDepositRequestsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/deposit': {
      id: '/dashboard/deposit'
      path: '/deposit'
      fullPath: '/dashboard/deposit'
      preLoaderRoute: typeof DashboardDepositRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/data-deletion-instructions': {
      id: '/auth/data-deletion-instructions'
      path: '/auth/data-deletion-instructions'
      fullPath: '/auth/data-deletion-instructions'
      preLoaderRoute: typeof AuthDataDeletionInstructionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify/': {
      id: '/auth/verify/'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify/success': {
      id: '/auth/verify/success'
      path: '/auth/verify/success'
      fullPath: '/auth/verify/success'
      preLoaderRoute: typeof AuthVerifySuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify/pending': {
      id: '/auth/verify/pending'
      path: '/auth/verify/pending'
      fullPath: '/auth/verify/pending'
      preLoaderRoute: typeof AuthVerifyPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/common/notifications/': {
      id: '/api/common/notifications/'
      path: '/api/common/notifications'
      fullPath: '/api/common/notifications'
      preLoaderRoute: typeof ApiCommonNotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/wallet/balance': {
      id: '/api/users/wallet/balance'
      path: '/api/users/wallet/balance'
      fullPath: '/api/users/wallet/balance'
      preLoaderRoute: typeof ApiUsersWalletBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/deposit/request': {
      id: '/api/users/deposit/request'
      path: '/api/users/deposit/request'
      fullPath: '/api/users/deposit/request'
      preLoaderRoute: typeof ApiUsersDepositRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/common/notifications/all': {
      id: '/api/common/notifications/all'
      path: '/api/common/notifications/all'
      fullPath: '/api/common/notifications/all'
      preLoaderRoute: typeof ApiCommonNotificationsAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/deposit/requests': {
      id: '/api/admin/deposit/requests'
      path: '/api/admin/deposit/requests'
      fullPath: '/api/admin/deposit/requests'
      preLoaderRoute: typeof ApiAdminDepositRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardDepositRoute: typeof DashboardDepositRoute
  DashboardDepositRequestsRoute: typeof DashboardDepositRequestsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDepositRoute: DashboardDepositRoute,
  DashboardDepositRequestsRoute: DashboardDepositRequestsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface GamesRouteChildren {
  GamesBlackjackRoute: typeof GamesBlackjackRoute
  GamesCrashRoute: typeof GamesCrashRoute
  GamesDiamondsRoute: typeof GamesDiamondsRoute
  GamesDiceRoute: typeof GamesDiceRoute
  GamesGoalRoute: typeof GamesGoalRoute
  GamesHiloRoute: typeof GamesHiloRoute
  GamesKenoRoute: typeof GamesKenoRoute
  GamesLimboRoute: typeof GamesLimboRoute
  GamesMinesRoute: typeof GamesMinesRoute
  GamesPlinkoRoute: typeof GamesPlinkoRoute
  GamesRouletteRoute: typeof GamesRouletteRoute
  GamesTowersRoute: typeof GamesTowersRoute
  GamesVideoPokerRoute: typeof GamesVideoPokerRoute
  GamesWheelRoute: typeof GamesWheelRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesBlackjackRoute: GamesBlackjackRoute,
  GamesCrashRoute: GamesCrashRoute,
  GamesDiamondsRoute: GamesDiamondsRoute,
  GamesDiceRoute: GamesDiceRoute,
  GamesGoalRoute: GamesGoalRoute,
  GamesHiloRoute: GamesHiloRoute,
  GamesKenoRoute: GamesKenoRoute,
  GamesLimboRoute: GamesLimboRoute,
  GamesMinesRoute: GamesMinesRoute,
  GamesPlinkoRoute: GamesPlinkoRoute,
  GamesRouletteRoute: GamesRouletteRoute,
  GamesTowersRoute: GamesTowersRoute,
  GamesVideoPokerRoute: GamesVideoPokerRoute,
  GamesWheelRoute: GamesWheelRoute,
  GamesIndexRoute: GamesIndexRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  GamesRoute: GamesRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AuthDataDeletionInstructionsRoute: AuthDataDeletionInstructionsRoute,
  AuthErrorRoute: AuthErrorRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AuthVerifyPendingRoute: AuthVerifyPendingRoute,
  AuthVerifySuccessRoute: AuthVerifySuccessRoute,
  AuthVerifyIndexRoute: AuthVerifyIndexRoute,
  ApiAdminDepositRequestsRoute: ApiAdminDepositRequestsRoute,
  ApiCommonNotificationsAllRoute: ApiCommonNotificationsAllRoute,
  ApiUsersDepositRequestRoute: ApiUsersDepositRequestRoute,
  ApiUsersWalletBalanceRoute: ApiUsersWalletBalanceRoute,
  ApiCommonNotificationsIndexRoute: ApiCommonNotificationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
